version: '3.3'
services:
  gamestore-web:
    build:
      context: .
      dockerfile: GameStore.WebUI/Dockerfile
    image: gamestore-web:latest
    depends_on:
      - redis
      - mysql
    networks:
      - front-tier
      - back-tier
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__GameStoreDatabase= server=mysql;userid=root;password=pass;database=game_store_db;
      - ConnectionStrings__GameStoreIdentityDatabase= server=mysql;userid=root;password=pass;database=game_store_identity_db;
      - Redis__Configuration= redis
      - RedisKeys__Configuration= redis
      - Advertisement_API= http://gamestore-advertisement-api/
    ports:
      - "80"
  gamestore-advertisement-api:
    build:
      context: .
      dockerfile: GameStore.API.Advertisement/Dockerfile
    image: gamestore-advertisement-api:latest
    networks:
      - back-tier
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "80"
  redis:
    image: redis
    ports:
       - "6379:6379"
    volumes:
     - redis-data:/data
    networks:
     - back-tier
  mysql:
    image: mysql/mysql-server:5.7
    ports:
       - "3306:3306"
    command: "--skip-grant-tables"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
     - back-tier
    environment:
      MYSQL_ROOT_PASSWORD: pass
  loadbalancer:
    image: 'dockercloud/haproxy:latest'
    links:
      - gamestore-web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80
    networks:
      - front-tier

volumes:
  redis-data:
    driver: local
  mysql-data:

networks:
  front-tier:
    driver: bridge
  back-tier:
    driver: bridge