jobs:
  test:
    docker:
      - image: docker:17.05.0-ce-git
    steps: 
      - checkout
      - setup_remote_docker
      - run: 
         name: Build and run unit tests
         command: |
           docker build --pull -t gamestore:unittests -f ./GameStore.UnitTests/Dockerfile .
           docker run --name gamestore-tests gamestore:unittests
           docker cp gamestore-tests:/app/GameStore.UnitTests/TestResults ./
      - store_test_results:
         path: TestResults
  build-web:
    executor: gcp-gcr/default
    steps:
      - checkout
      - gcp-gcr/gcr-auth
      - gcp-gcr/build-image:
          context: .
          image: gamestore-web
          registry-url: us.gcr.io
      - gcp-gcr/push-image:
          digest-path: /tmp/digest.txt
          image: gamestore-web
          registry-url: eu.gcr.io
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"

orbs:
  gcp-gcr: circleci/gcp-gcr@0.7.1
version: 2.1
workflows:
  commit:
    jobs:
      - build-web