version: 2 
jobs: 
 build: 
   docker: 
     - image: docker:18.09.3
   steps: 
     - checkout 
     - setup_remote_docker: 
        docker_layer_caching: true 
     - run: 
        name: Build and run unit tests
        command: |
          docker build --pull -t gamestore:unittests -f ./GameStore.UnitTests/Dockerfile .
          mkdir test-results
          docker run --rm -v test-results:/app/GameStore.UnitTests/TestResults gamestore:unittests
     - store_test_results:
        path: test-results
