version: 2 
jobs:
  build:
    docker:
      - image: docker:17.05.0-ce-git
    steps: 
      - checkout
      - setup_remote_docker
      - run: 
         name: Build and run unit tests
         command: |
           docker build --pull -t gamestore:unittests -f ./GameStore.UnitTests/Dockerfile .
           docker run --name gamestore-tests gamestore:unittests
           docker cp gamestore-tests:/app/GameStore.UnitTests/TestResults ./
      - store_test_results:
         path: TestResults

workflows:
  version: 2
  build:
    jobs:
      - build
