version: 2 
jobs:
  build:
    docker:
      - image: docker:17.05.0-ce-git
    steps: 
      - checkout
      - setup_remote_docker
      - run: 
         name: Build and run unit tests
         command: |
           docker build --pull -t gamestore:unittests -f ./GameStore.UnitTests/Dockerfile .
           mkdir test-results
           docker run --rm -v test-results:/app/GameStore.UnitTests/TestResults gamestore:unittests
      - store_test_results:
         path: test-results

workflows:
  version: 2
  build:
    jobs:
      - build
